version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ${PWD}/static:/app/static
      - ${PWD}/templates:/app/templates
      
    environment:
      FLASK_ENV: development
